import type { AgentToolName } from "./definitions";

const LABELS: Record<AgentToolName, string> = {
  create_tool: "Researching website and creating draft…",
  create_tools: "Creating multiple tool drafts…",
  update_tool: "Refreshing tool from website…",
  list_tools: "Searching tools…",
  set_tool_listing_type: "Updating listing type…",
  get_tool_issues: "Checking catalog issues…",
  feature_tool: "Updating featured status…",
  create_category: "Creating category…",
  list_categories: "Loading categories…",
  create_blog_draft: "Writing blog draft…",
  suggest_content_ideas: "Brainstorming content ideas…",
  plan_marketing: "Planning marketing…",
  list_blog_posts: "Loading blog posts…",
  publish_blog: "Updating blog publish status…",
  update_blog_post: "Updating blog post…",
  delete_blog_post: "Preparing blog delete…",
  publish_tool: "Updating publish status…",
  delete_tool: "Preparing delete…",
  list_affiliates: "Searching affiliate CRM…",
  list_affiliate_directory: "Loading affiliate directory…",
  update_affiliate: "Updating affiliate program…",
  create_affiliate: "Creating affiliate program…",
  create_tool_from_affiliate: "Creating tool from affiliate…",
  get_analytics: "Loading analytics…",
  get_my_work: "Loading your work queue…",
  get_finance_summary: "Loading finance summary…",
  search_audit_log: "Searching audit log…",
  list_subscribers: "Loading subscribers…",
  list_tasks: "Loading tasks…",
  create_task: "Creating task…",
  update_task: "Updating task…",
  delete_task: "Preparing task delete…",
  create_finance_entry: "Adding finance entry…",
  list_finance_entries: "Loading finance entries…",
  update_finance_entry: "Updating finance entry…",
  delete_finance_entry: "Preparing finance delete…",
  list_team_members: "Loading team…",
  list_notes: "Loading notes…",
  get_note: "Opening note…",
  create_note: "Creating note…",
  update_note: "Updating note…",
  delete_note: "Preparing note delete…",
  search_playbook: "Searching playbook…",
  create_playbook_snippet: "Adding playbook snippet…",
  update_playbook_snippet: "Updating playbook snippet…",
  delete_playbook_snippet: "Preparing playbook delete…",
};

export function toolProgressLabel(tool: AgentToolName): string {
  return LABELS[tool] ?? `Running ${tool.replace(/_/g, " ")}…`;
}
