export const AFFILIATE_CATEGORIES = [
  "Web Hosting",
  "Domains & Hosting",
  "Email Marketing",
  "Email & CRM",
  "CRM",
  "CRM & Marketing",
  "Design Tool",
  "Graphic Design",
  "Photo Editing",
  "Infographic Tool",
  "Visual Content",
  "Automation",
  "Productivity",
  "SEO Tool",
  "SEO / Marketing Suite",
  "Marketing & SEO",
  "Sales Funnels",
  "Lead Generation",
  "Ecommerce Platform",
  "E-Commerce",
  "Ecommerce App",
  "Digital Sales",
  "Online Courses",
  "Online Course Platform",
  "Online Learning",
  "Online Learning Marketplace",
  "All-in-One Platform",
  "All-in-One Learning",
  "Affiliate Network",
  "Affiliate Marketing SaaS",
  "VPN / Cybersecurity",
  "Cybersecurity",
  "Password Manager",
  "Reviews & UGC",
  "Newsletter Platform",
  "Email / Creator",
  "Creator Monetization",
  "Podcast Distribution",
  "Website Builder",
] as const;

export type AffiliateCategory = (typeof AFFILIATE_CATEGORIES)[number];
